# Generated by Django 3.2 on 2023-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_auto_20231205_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='readtext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
